kind: pipeline
name: default

steps:
- name: setup
  image: gdritter/lament-configuration-env:latest
  commands:
  - poetry config virtualenvs.in-project true
  - poetry install

- name: format
  image: gdritter/lament-configuration-env:latest
  commands:
  - inv checkfmt

- name: typecheck
  image: gdritter/lament-configuration-env:latest
  commands:
  - inv tc

- name: test
  image: gdritter/lament-configuration-env:latest
  commands:
  - inv test
