kind: pipeline
name: default

steps:
- name: setup
  image: python
  commands:
  - python3 -m virtualenv .
  - source ./bin/activate
  - pip install poetry
  - pip install invoke
  - poetry config virtualenvs.in-project true --local
  - poetry install

- name: test
  image: python
  commands:
  - source ./bin/activate
  - inv test

- name: typecheck
  image: python
  commands:
  - source ./bin/activate
  - poetry run inv tc

- name: format
  image: python
  commands:
  - source ./bin/activate
  - poetry run inv checkfmt
