kind: pipeline
name: default

steps:
- name: setup
  image: gdritter/lament-configuration-env:latest
  commands:
  - poetry config virtualenvs.in-project true
  - poetry install

- name: format
  image: gdritter/lament-configuration-env:latest
  commands:
  - inv checkfmt

- name: typecheck
  image: gdritter/lament-configuration-env:latest
  commands:
  - inv tc

- name: test
  image: gdritter/lament-configuration-env:latest
  commands:
  - inv test

- name: slack
  image: plugins/slack
  settings:
    webhook: https://mm.infinitenegativeutility.com/hooks/9kz3ro474bnj7kgqxw7r9qmaxr
    channel: lament-configuration
