kind: pipeline
name: default

steps:
- name: setup
  image: python
  commands:
  - pip install poetry
  - pip install invoke
  - poetry config virtualenvs.in-project true --local
  - poetry install

- name: test
  image: python
  commands:
  - poetry run inv test

- name: typecheck
  image: python
  commands:
  - poetry run inv tc

- name: format
  image: python
  commands:
  - poetry run inv checkfmt
