kind: pipeline
name: default

workspace:
  path: /root

steps:
- name: setup
  image: python
  commands:
  - pip install poetry --user
  - pip install invoke --user
  - poetry config virtualenvs.in-project true --local
  - poetry install

- name: test
  image: python
  commands:
  - inv test

- name: typecheck
  image: python
  commands:
  - poetry run inv tc

- name: format
  image: python
  commands:
  - poetry run inv checkfmt
