kind: pipeline
name: default

workspace:
  path: /root

steps:
- name: setup
  image: python
  environment:
    PIP_TARGET: '/root/.pip'
  commands:
  - pip install poetry
  - pip install invoke
  - export PATH=/root/.pip:$PATH
  - poetry config virtualenvs.in-project true --local
  - poetry install

- name: test
  image: python
  environment:
    PIP_TARGET: '/root/.pip'
  commands:
  - export PATH=/root/.pip:$PATH
  - inv test

- name: typecheck
  image: python
  environment:
    PIP_TARGET: '/root/.pip'
  commands:
  - export PATH=/root/.pip:$PATH
  - poetry run inv tc

- name: format
  image: python
  environment:
    PIP_TARGET: '/root/.pip'
  commands:
  - export PATH=/root/.pip:$PATH
  - poetry run inv checkfmt
