kind: pipeline
name: default

workspace:
  path: /root

steps:
- name: test_all
  image: python
  commands:
  - pip install poetry
  - poetry install
  - poetry run inv test
  - poetry run inv tc
  - poetry run inv checkfmt
